### ISSUE TITLE
Hitting issues with this with Node12 and WiringPi compiling

### ISSUE THREAD

**Issue by chriskinsman** [globalroo/blinkt-kit#1]
I ported all the wiring pi code jperkin/rpio for my own use and have it all working.  Wondering if a pull request of this would be welcomed?  @globalroo thoughts?

**Comment by globalroo** [comment]
Yes @chriskinsman, absolutely!

**Comment by chriskinsman** [comment]
As soon as they accept a pull request over at @jperkin/rpio I will send in a pull request
