### ISSUE TITLE
Please add to npmjs collaborators

### ISSUE THREAD

**Issue by chriskinsman** [globalroo/blinkt-kit#6]
@globalroo Please add to npmjs collaborators so I can publish the package.  

chriskinsman is my npmjs identity.

Thanks,

Chris

**Comment by globalroo** [comment]
Hi Chris, 

Apologies - I added you yesterday, but their UI always trips me up with the 'update package settings' being above the invite collaborators! You should be good to go now.

Have a good day :)

Andy

**Comment by chriskinsman** [comment]
Thanks!  You too!
